/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/add-icon.vue')['default']
    AppHeader: typeof import('./src/components/layout/app-header.vue')['default']
    BaseButton: typeof import('./src/components/primitives/base-button.vue')['default']
    CloseIcon: typeof import('./src/components/icons/close-icon.vue')['default']
    DataList: typeof import('./src/components/advanced/data-list.vue')['default']
    DotsIcon: typeof import('./src/components/icons/dots-icon.vue')['default']
    FormField: typeof import('./src/components/primitives/form-field.vue')['default']
    GhostButton: typeof import('./src/components/primitives/ghost-button.vue')['default']
    CheckboxInput: typeof import('./src/components/primitives/checkbox-input.vue')['default']
    IconButton: typeof import('./src/components/primitives/icon-button.vue')['default']
    InitialsIcon: typeof import('./src/components/primitives/initials-icon.vue')['default']
    LoadingAll: typeof import('./src/components/loading/loading-all.vue')['default']
    LoadingTest: typeof import('./src/components/loading/loading-test.vue')['default']
    MailIcon: typeof import('./src/components/icons/mail-icon.vue')['default']
    ModalHeader: typeof import('./src/components/layout/modal-header.vue')['default']
    MoreInfoButton: typeof import('./src/components/primitives/more-info-button.vue')['default']
    OutlineButton: typeof import('./src/components/primitives/outline-button.vue')['default']
    PersonIcon: typeof import('./src/components/icons/person-icon.vue')['default']
    PhoneIcon: typeof import('./src/components/icons/phone-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/search-icon.vue')['default']
    SelectBox: typeof import('./src/components/primitives/select-box.vue')['default']
    SidebarNav: typeof import('./src/components/sidebar-nav.vue')['default']
    TabNav: typeof import('./src/components/primitives/tab-nav.vue')['default']
    TextInput: typeof import('./src/components/primitives/text-input.vue')['default']
    ThumbDownIcon: typeof import('./src/components/icons/thumb-down-icon.vue')['default']
    ThumbUpIcon: typeof import('./src/components/icons/thumb-up-icon.vue')['default']
  }
}
