/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/app-header.vue')['default']
    BaseButton: typeof import('./src/components/primitives/base-button.vue')['default']
    DataList: typeof import('./src/components/advanced/data-list.vue')['default']
    DotsIcon: typeof import('./src/components/icons/dots-icon.vue')['default']
    IconButton: typeof import('./src/components/primitives/icon-button.vue')['default']
    LoadingAll: typeof import('./src/components/loading/loading-all.vue')['default']
    LoadingTest: typeof import('./src/components/loading/loading-test.vue')['default']
    MailIcon: typeof import('./src/components/icons/mail-icon.vue')['default']
    MoreInfoButton: typeof import('./src/components/primitives/more-info-button.vue')['default']
    PersonIcon: typeof import('./src/components/icons/person-icon.vue')['default']
    PhoneIcon: typeof import('./src/components/icons/phone-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/search-icon.vue')['default']
    SidebarNav: typeof import('./src/components/sidebar-nav.vue')['default']
    SkeletonLayout: typeof import('./src/components/primitives/skeleton-layout.vue')['default']
    SkeletonTest: typeof import('./src/components/primitives/skeleton-test.vue')['default']
    TabNav: typeof import('./src/components/primitives/tab-nav.vue')['default']
    TextInput: typeof import('./src/components/primitives/text-input.vue')['default']
  }
}
